#!/bin/bash
python3 main.py --target amazon --method dd --classname 0  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 1 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 2 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 3 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 4 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 5 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 6 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 7 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 8 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 9 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 10  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 11 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 12 --experiment_name  dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 13 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 14 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 15 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 16 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 17 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 18 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 19 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 20  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 21 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 22 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 23 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 24 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 25 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 26 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 27 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 28 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 29 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method dd --classname 30 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 0 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 1 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 2 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 3 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 4 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 5 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 6 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 7 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 8 --experiment_name  dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 9 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 10 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 11 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 12 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 13 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 14 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 15 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 16 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 17 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 18 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 19 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 20 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 21 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 22 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 23 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 24 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 25 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 26 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 27 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 28 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 29 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method balanedsourcetarget --classname 30 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 0  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 1 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 2 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 3 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 4 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 5 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 6 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 7 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 8 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 9 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 10  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 11 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 12 --experiment_name  dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 13 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 14 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 15 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 16 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 17 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 18 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 19 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 20  --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 21 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 22 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 23 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 24 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 25 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 26 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 27 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 28 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 29 --experiment_name dslr_to_amazon  --source dslr
python3 main.py --target amazon --method justsource --classname 30 --experiment_name dslr_to_amazon  --source dslr
